apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ingress-nginx